spring.application.name=diabetes-backend
server.address=0.0.0.0
server.port=8080

#Vercel configaration
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OAuth2 client configuration (Google)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/auth/oauth2/callback/google
spring.security.oauth2.client.registration.google.scope=email,profile

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://glucopal-peach.vercel.app

cors.allowed-methods=GET,POST,PUT,DELETE
cors.allowed-headers=*
cors.allow-credentials=true

# Application-specific properties
jwt.secret=${JWT_SECRET:glucopal-super-secret-jwt-key-2026-do-not-share}
jwt.expiration=${JWT_EXPIRATION:86400000}
#Python AI microservice URL
python.ai.service.url=${PYTHON_SERVICE_URL:http://localhost:8000}

#Logging
logging.level.com.diabetesapp=DEBUG

#Health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never




